---
scenario:
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - lint
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - destroy
  destroy_sequence:
    - cleanup
    - destroy
  converge_sequence:
    - create
    - prepare
    - converge
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: geosword.xorg
    groups:
      - arch
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: "'vagrant'"
    box: archlinux/archlinux
    priveleged: true
    memory: 2048
    cpus: 1
#    provision: no
provisioner:
  name: ansible
verifier:
  name: ansible
