---
- hosts: all
  gather_facts: true
  become: true
  tasks:

    - name: "check for python"
      raw: "test -e /usr/bin/python || /usr/bin/pacman -Sy --noconfirm python python-pip"
      changed_when: false

    - name: update everything
      command: /usr/bin/pacman -Syu --noconfirm

    - name: install some things which arent in the container but are in the tar image
      raw: /usr/bin/pacman -S --noconfirm vim base-devel

    - name: some things that need doing in virtualbox, before we start configuring xorg
      include: virtualboxdrivers.yml

    - name: "Include the pre-req roles"
      include_role:
        apply:
          become: true
        name: "{{ preprole }}"
      loop_control:
        loop_var: preprole
      loop:
        - "grog.user"
        - "grog.authorized-key"
        - "geosword.workstation-base"

#        Helpful environment variables
#        PY_COLORS=1|0
#        ANSIBLE_FORCE_COLOR=1|0
#
#        MOLECULE_NO_LOG=false - if you get an error during setup but it says no_log: is true
#
#        Molecule runtime environment variables:
#        MOLECULE_FILE=/home/dylanh/.cache/molecule/ansible.rolewebserver/default/molecule.yml
#        MOLECULE_VERIFIER_NAME=ansible
#        MOLECULE_DEPENDENCY_NAME=galaxy
#        MOLECULE_SCENARIO_DIRECTORY=/home/dylanh/development/ansible.rolewebserver/molecule/default
#        MOLECULE_INVENTORY_FILE=/home/dylanh/.cache/molecule/ansible.rolewebserver/default/inventory/ansible_inventory.yml
#        MOLECULE_INSTANCE_CONFIG=/home/dylanh/.cache/molecule/ansible.rolewebserver/default/instance_config.yml
#        MOLECULE_PROVISIONER_NAME=ansible
#        MOLECULE_DEBUG=False
#        MOLECULE_DRIVER_NAME=docker
#        MOLECULE_VERIFIER_TEST_DIRECTORY=/home/dylanh/development/ansible.rolewebserver/molecule/default/molecule
#        MOLECULE_STATE_FILE=/home/dylanh/.cache/molecule/ansible.rolewebserver/default/state.yml
#        MOLECULE_SCENARIO_NAME=default
#        MOLECULE_ENV_FILE=/home/dylanh/development/ansible.rolewebserver/.env.yml
#        MOLECULE_PROJECT_DIRECTORY=/home/dylanh/development/ansible.rolewebserver
#        MOLECULE_EPHEMERAL_DIRECTORY=/home/dylanh/.cache/molecule/ansible.rolewebserver/default
