---
- src: grog.user
- src: grog.authorized-key
- src: git@github.com:geosword/ansible-role-ws-base.git
  scm: git
  version: master
  name: geosword.workstation-base
- src: git@github.com:geosword/ansible-role-nvidia.git
  scm: git
  version: master
  name: geosword.nvidia
